use_frameworks!
platform:ios, '10.0'


target 'Wildlink_Example' do
  pod 'Wildlink', :path => '../'

  target 'Wildlink_ExampleTests' do
    pod 'Wildlink', :path => '../', :testspecs => ['Tests']
  end
end
