use_frameworks!
platform:ios, '10.0'


target 'Wildlink_Example' do
  pod 'Wildlink', :path => '../'

  target 'Wildlink_ExampleTests' do
    pod 'Wildlink', :path => '../', :testspecs => ['Tests']
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
