name: CI Publish
on:
  push:
    tags:
      - '*'

jobs:
  pod-lint:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Cache CocoaPods data
        uses: actions/cache@v3
        with:
          path: Example/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Run pod lib lint
        run: |
          bundle install
          bundle exec fastlane lint
  unit-tests:
    runs-on: macos-latest
    needs: pod-lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Cache CocoaPods data
        uses: actions/cache@v3
        with:
          path: Example/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Run the unit tests
        run: |
          bundle install
          bundle exec fastlane test
  # Since this runs free on hosted runners, don't optimize for minimum
  # runtime. Instead, make sure we never publish something that doesn't
  # pass both lint and unit testing, even after merges.
  publish:
    runs-on: macos-latest
    needs: unit-tests
    steps:
      - name: Collect Secrets
        id: op-load-secret
        uses: 1password/load-secrets-action@v1.3.1
        with:
          export-env: true
        env:
          # Using SA: Automation Secrets, ID: y4mrwo3yadv72iwv3ijea2phfe
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          COCOAPODS_TRUNK_TOKEN: op://zbd36f6x6na5fczi43zkwes44y/zjsytd67inhsxkufmpxtukdojq/credential
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Publish to CocoaPods trunk
        run: |
          bundle install
          bundle exec fastlane publish
