name: GitHub Actions CI
on: [push]
jobs:
  pod-lint:
    runs-on: macos-11
    steps:
      - name: Select Xcode 13
        uses: devbotsxyz/xcode-select@v1
        with:
          version: '13'
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Cache CocoaPods data
        uses: actions/cache@v3
        with:
          path: Example/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Run pod lib lint
        run: |
          bundle install
          bundle exec fastlane lint
  unit-tests:
    runs-on: macos-11
    needs: pod-lint
    steps:
      - name: Select Xcode 13
        uses: devbotsxyz/xcode-select@v1
        with:
          version: '13'
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Cache CocoaPods data
        uses: actions/cache@v3
        with:
          path: Example/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Run the unit tests
        run: |
          bundle install
          bundle exec fastlane test
